const works=window.HOPPANG_WORKS||[], cfg=window.HOPPANG_CONFIG||{}, Auth=window.HoppangAuth;
const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const store={get(k,d=null){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const prefs=Object.assign({theme:'dark',fontSize:19,lineHeight:1.9,width:760,font:'serif'},store.get('hoppang:prefs',{}));
let authState={user:null,purchases:[],configured:false}, selectedGenre='전체';
function money(n){return new Intl.NumberFormat('ko-KR').format(n)+'원'}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function toast(msg){const el=$('#toast');el.textContent=msg;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,2400)}
function applyPrefs(){const r=document.documentElement;r.classList.toggle('light',prefs.theme==='light');r.style.setProperty('--reader-size',prefs.fontSize+'px');r.style.setProperty('--reader-lh',prefs.lineHeight);r.style.setProperty('--reader-width',prefs.width+'px');$('.reader-article')?.classList.toggle('sans',prefs.font==='sans');if($('#fontSize')){$('#fontSize').value=prefs.fontSize;$('#fontSizeOut').textContent=prefs.fontSize+'px';$('#lineHeight').value=prefs.lineHeight;$('#lineHeightOut').textContent=Number(prefs.lineHeight).toFixed(2);$('#readerWidth').value=prefs.width;$('#widthOut').textContent=prefs.width+'px';$$('#fontMode button').forEach(b=>b.classList.toggle('active',b.dataset.font===prefs.font))}}
function savePrefs(){store.set('hoppang:prefs',prefs);applyPrefs()} applyPrefs();
function genres(){return ['전체',...new Set(works.flatMap(w=>w.genre))]}
function coverHTML(w,small=false){return `<div class="cover ${w.cover} ${small?'continue-thumb':''}"><div class="cover-price">₩${w.price.toLocaleString()}</div><div class="cover-copy"><span class="cover-kicker">${w.badge}</span><div class="cover-title">${w.title}</div><div class="cover-sub">${w.subtitle}</div></div></div>`}
function footer(){return `<footer class="footer"><span>© 2026 호빵문고 · 오리지널 디지털 콘텐츠</span><span><a href="legal.html">이용약관 · 개인정보 안내</a> · 실제 결제는 PG/백엔드 설정 후 활성화</span></footer>`}
function owned(w){return Auth?.owns(w.id)||false}
function lastRead(){return store.get('hoppang:lastRead',null)}
function workCard(w){return `<a class="work-card" href="#/work/${w.id}">${coverHTML(w)}<div class="work-info"><div class="work-card-top"><h3>${w.title}</h3><b class="price">${owned(w)?'소장중':money(w.price)}</b></div><p>${w.subtitle}</p><div class="chips">${w.genre.slice(0,3).map(g=>`<span class="chip">${g}</span>`).join('')}</div></div></a>`}
function purchaseCTA(w){if(owned(w))return `<a class="primary-btn" href="#/read/${w.id}/0">✓ 소장중 · 읽기</a>`;return `<button class="primary-btn buy-btn" data-buy="${w.id}">₩${w.price.toLocaleString()} 구매하기</button>`}
function home(){const f=works[0],lr=lastRead();let cont='';if(lr){const w=works.find(x=>x.id===lr.workId);if(w&&owned(w)){const c=w.chapters[lr.chapter]||w.chapters[0];cont=`<section class="section"><div class="section-head"><div><span class="eyebrow">CONTINUE</span><h2>계속 읽기</h2></div></div><div class="continue-card"><a href="#/work/${w.id}">${coverHTML(w,true)}</a><div class="continue-meta"><small>${w.title}</small><h3>${c.title}</h3><div class="mini-progress"><span style="width:${Math.round((lr.progress||0)*100)}%"></span></div></div><a class="primary-btn" href="#/read/${w.id}/${lr.chapter}">이어 읽기 →</a></div></section>`}}
return `<section class="hero"><div class="hero-copy"><span class="eyebrow">HOPPANG ORIGINAL · DIGITAL STORE</span><h1>한 번 소장하고,<br><em>끝까지 읽는다.</em></h1><p>${f.description}</p><div class="hero-price"><strong>${money(f.price)}</strong><span>1회 구매 · 소장형 디지털 콘텐츠</span></div><div class="actions">${purchaseCTA(f)}<a class="secondary-btn" href="#/work/${f.id}">작품 정보</a></div></div><div class="hero-art">${coverHTML(f)}</div></section>${cont}<section class="section"><div class="section-head"><div><span class="eyebrow">ORIGINALS</span><h2>지금 읽을 작품</h2><p>장르별로 찾고, 1,000원에 소장하세요.</p></div><a class="text-link" href="#/catalog">장르 탐색 →</a></div><div class="works-grid">${works.map(workCard).join('')}</div></section><section class="feature-strip"><div><b>장르 탐색</b><span>로맨스부터 미스터리, 병맛 코미디까지</span></div><div><b>계정 서재</b><span>구매 작품과 독서 기록을 한곳에</span></div><div><b>Toss Payments</b><span>카드·간편결제 UI 연동 준비</span></div></section>${footer()}`}
function catalog(){const gs=genres();const filtered=selectedGenre==='전체'?works:works.filter(w=>w.genre.includes(selectedGenre));return `<div class="page-wrap"><span class="eyebrow">DISCOVER</span><h1 class="page-title">장르별 탐색</h1><p class="page-desc">취향에 맞는 이야기를 고르세요. 모든 작품의 판매가는 ${money(cfg.PRICE_KRW||1000)}입니다.</p><div class="genre-tabs">${gs.map(g=>`<button class="genre-tab ${g===selectedGenre?'active':''}" data-genre="${g}">${g}</button>`).join('')}</div><div class="catalog-toolbar"><span>${filtered.length}개 작품</span><button class="secondary-btn" onclick="openSearch()">⌕ 상세 검색</button></div><div class="works-grid library-grid">${filtered.map(workCard).join('')}</div></div>${footer()}`}
function storePage(){return `<div class="page-wrap"><span class="eyebrow">STORE</span><h1 class="page-title">1,000원 스토어</h1><p class="page-desc">작품을 한 번 구매하면 로그인한 계정의 내 서재에 등록됩니다.</p><div class="store-grid">${works.map(w=>`<div class="store-row">${coverHTML(w,true)}<div class="store-copy"><div class="chips">${w.genre.map(g=>`<span class="chip">${g}</span>`).join('')}</div><h2>${w.title}</h2><p>${w.description}</p><div class="store-bottom"><strong>${money(w.price)}</strong>${purchaseCTA(w)}</div></div></div>`).join('')}</div><div class="info-box"><strong>실결제 연동 안내</strong><p>브라우저에는 토스 클라이언트 키만 사용하고, 결제 승인용 시크릿 키는 별도 서버의 환경변수에만 보관합니다. 현재 설정이 비어 있으면 결제 버튼이 설정 안내를 보여줍니다.</p></div></div>${footer()}`}
function workDetail(id){const w=works.find(x=>x.id===id);if(!w)return notFound();const own=owned(w);const lr=lastRead(),start=lr&&lr.workId===w.id?lr.chapter:0;return `<section class="detail-hero"><div class="detail-cover">${coverHTML(w)}</div><div class="detail-copy"><span class="eyebrow">${w.badge} · ${w.status}</span><h1>${w.title}</h1><p class="subtitle">${w.subtitle}</p><div class="meta-row"><span class="meta-pill">${w.genre.join(' · ')}</span><span class="meta-pill">${w.rating}</span><span class="meta-pill">${w.chapters.length}화</span></div><p class="desc">${w.description}</p><div class="quote">“${w.quote}”</div><div class="characters">${w.characters.map(c=>`<span class="character">${c}</span>`).join('')}</div><div class="price-panel"><div><small>판매가</small><strong>${money(w.price)}</strong></div><span>${own?'내 서재에 등록된 작품입니다.':'로그인 후 구매할 수 있습니다.'}</span></div><div class="actions">${own?`<a class="primary-btn" href="#/read/${w.id}/${start}">${start>0?'▶ 이어 읽기':'▶ 읽기 시작'}</a>`:purchaseCTA(w)}<button class="secondary-btn" onclick="openSearch('${escapeHTML(w.title)}')">⌕ 작품 내 검색</button></div></div></section><section class="chapter-section"><div class="section-head"><div><h2>목차</h2><p>${own?'전 화 열람 가능':`미구매 상태 · ${w.previewChapters?`${w.previewChapters}화 미리보기 제공`:'상세 페이지 미리보기만 제공'}`}</p></div></div><div class="chapter-list">${w.chapters.map((c,i)=>{const lock=!own&&i>=w.previewChapters;return `<a class="chapter-row ${lock?'locked':''}" href="${lock?'javascript:void(0)':`#/read/${w.id}/${i}`}" ${lock?`data-buy="${w.id}"`:''}><span class="chapter-num">${String(i+1).padStart(2,'0')}</span><strong>${c.title}</strong><span>${lock?'🔒 구매 후 열람':(own?'읽기 →':'미리보기 →')}</span></a>`}).join('')}</div></section>${footer()}`}
function reader(id,idx){const w=works.find(x=>x.id===id);idx=Number(idx)||0;if(!w||!w.chapters[idx])return notFound();if(!owned(w)&&idx>=w.previewChapters)return `<div class="paywall"><div class="paywall-card">${coverHTML(w,true)}<span class="eyebrow">LOCKED CHAPTER</span><h1>구매 후 계속 읽을 수 있어요.</h1><p>${w.title} 전편을 ${money(w.price)}에 소장하고 계속 읽어보세요.</p>${purchaseCTA(w)}<a class="secondary-btn" href="#/work/${w.id}">작품 정보</a></div></div>`;const c=w.chapters[idx];setTimeout(()=>{applyPrefs();restoreScroll(w.id,idx)},0);return `<section class="reader-shell"><div class="reader-top"><div class="book-name"><a href="#/work/${w.id}">← ${w.title}</a></div><div class="chapter-name">${c.title}</div><div class="reader-actions"><button class="icon-btn" id="bookmarkBtn">☆</button><button class="icon-btn" id="settingsBtn">Aa</button></div></div><article class="reader-article"><header class="reader-title"><small>${owned(w)?'소장본':'무료 미리보기'}</small><h1>${c.title}</h1><p>${idx+1} / ${w.chapters.length}</p></header>${c.paragraphs.map(p=>`<p class="${p.includes('\n')?'poem':''}">${escapeHTML(p).replace(/\n/g,'<br>')}</p>`).join('')}<div class="reader-footer">${idx>0?`<a class="nav-chapter" href="#/read/${w.id}/${idx-1}"><small>← 이전</small>${w.chapters[idx-1].title}</a>`:'<span></span>'}${idx<w.chapters.length-1?(owned(w)||idx+1<w.previewChapters?`<a class="nav-chapter next" href="#/read/${w.id}/${idx+1}"><small>다음 →</small>${w.chapters[idx+1].title}</a>`:`<button class="nav-chapter next buy-link" data-buy="${w.id}"><small>다음 화 잠금</small>${money(w.price)} 구매하기</button>`):`<a class="nav-chapter next" href="#/work/${w.id}"><small>완독</small>작품 정보로</a>`}</div></article></section>`}
function myLibrary(){if(!authState.user)return `<div class="page-wrap centered"><span class="eyebrow">MY LIBRARY</span><h1 class="page-title">로그인하면 내 서재를 사용할 수 있어요.</h1><p class="page-desc">구매 작품과 읽던 위치를 계정 기준으로 관리합니다.</p><button class="primary-btn" onclick="openAuth()">로그인 / 회원가입</button></div>${footer()}`;const mine=works.filter(owned);return `<div class="page-wrap"><span class="eyebrow">MY LIBRARY</span><h1 class="page-title">${authState.user.email?.split('@')[0]||'회원'}님의 서재</h1><p class="page-desc">구매한 작품 ${mine.length}권</p>${mine.length?`<div class="works-grid library-grid">${mine.map(workCard).join('')}</div>`:`<div class="empty-library"><h2>아직 구매한 작품이 없어요.</h2><p>스토어에서 첫 작품을 골라보세요.</p><a class="primary-btn" href="#/store">스토어 가기</a></div>`}</div>${footer()}`}
function profile(){return `<div class="page-wrap"><span class="eyebrow">ACCOUNT</span><h1 class="page-title">마이페이지</h1>${authState.user?`<div class="profile-card"><div class="avatar">${(authState.user.email||'?')[0].toUpperCase()}</div><div><h2>${escapeHTML(authState.user.email||'회원')}</h2><p>구매 작품 ${works.filter(owned).length}권 · 호빵문고 회원</p></div><button class="secondary-btn" id="logoutBtn">로그아웃</button></div>`:`<div class="profile-card"><div class="avatar">?</div><div><h2>게스트</h2><p>로그인하면 구매와 내 서재가 활성화됩니다.</p></div><button class="primary-btn" onclick="openAuth()">로그인</button></div>`}<div class="settings-grid"><button class="setting-card" id="profileTheme"><b>화면 테마</b><span>${prefs.theme==='dark'?'다크':'라이트'} 모드</span></button><a class="setting-card" href="legal.html"><b>약관 / 개인정보</b><span>판매 및 계정 운영 안내</span></a></div></div>${footer()}`}
function notFound(){return `<div class="page-wrap centered"><span class="eyebrow">404</span><h1 class="page-title">페이지를 찾지 못했어요.</h1><a class="primary-btn" href="#/">홈으로</a></div>`}
function route(){window.scrollTo(0,0);const p=(location.hash||'#/').slice(2).split('/');let v;if(p[0]==='work')v=workDetail(p[1]);else if(p[0]==='read')v=reader(p[1],p[2]);else if(p[0]==='catalog')v=catalog();else if(p[0]==='store')v=storePage();else if(p[0]==='my-library')v=myLibrary();else if(p[0]==='profile')v=profile();else v=home();$('#app').innerHTML=v;bindDynamic();updateNav(p[0]||'home')}
function bindDynamic(){$$('.genre-tab').forEach(b=>b.onclick=()=>{selectedGenre=b.dataset.genre;route()});$$('[data-buy]').forEach(b=>b.onclick=e=>{e.preventDefault();startPurchase(b.dataset.buy)});$('#settingsBtn')?.addEventListener('click',()=>{$('#readerPanel').hidden=false;applyPrefs()});$('#logoutBtn')?.addEventListener('click',async()=>{await Auth.signOut();toast('로그아웃했습니다.')});$('#profileTheme')?.addEventListener('click',()=>{prefs.theme=prefs.theme==='dark'?'light':'dark';savePrefs();route()});const bm=$('#bookmarkBtn');if(bm){const [,,wid,ci]=(location.hash||'').split('/'),key=`${wid}:${ci}`,marks=store.get('hoppang:bookmarks',[]);bm.textContent=marks.includes(key)?'★':'☆';bm.onclick=()=>{let m=store.get('hoppang:bookmarks',[]);m=m.includes(key)?m.filter(x=>x!==key):[...m,key];store.set('hoppang:bookmarks',m);bm.textContent=m.includes(key)?'★':'☆'}}}
function updateNav(p){$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===p));if(!['catalog','store','my-library'].includes(p))$('[data-nav="home"]')?.classList.toggle('active',p==='home'||!p)}
function restoreScroll(workId,chapter){const lr=lastRead();if(lr&&lr.workId===workId&&Number(lr.chapter)===Number(chapter)&&lr.scrollY)setTimeout(()=>window.scrollTo(0,Math.min(lr.scrollY,document.body.scrollHeight-innerHeight)),70)}
function trackReader(){const h=(location.hash||'').split('/');if(h[1]!=='read')return;const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);store.set('hoppang:lastRead',{workId:h[2],chapter:Number(h[3])||0,progress:Math.min(1,scrollY/max),scrollY,at:Date.now()})}
async function startPurchase(workId){const w=works.find(x=>x.id===workId);if(!w)return;if(owned(w)){location.hash=`#/read/${w.id}/0`;return}if(!authState.user){openAuth();toast('구매하려면 먼저 로그인해주세요.');return}if(!cfg.API_BASE_URL){toast('결제 백엔드 주소가 아직 설정되지 않았어요. README의 배포 단계를 확인하세요.');return}const token=await Auth.token();if(!token){openAuth();return}sessionStorage.setItem('hoppang:checkoutWork',workId);location.href=`checkout.html?work=${encodeURIComponent(workId)}`}
window.startPurchase=startPurchase;
function openSearch(seed=''){const l=$('#searchLayer');l.hidden=false;$('#searchGenres').innerHTML=genres().map(g=>`<button class="chip" data-sg="${g}">${g}</button>`).join('');$$('[data-sg]').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.sg==='전체'?'':b.dataset.sg;renderSearch($('#searchInput').value)});$('#searchInput').value=seed;renderSearch(seed);setTimeout(()=>$('#searchInput').focus(),30)} window.openSearch=openSearch;
function renderSearch(q){q=q.trim().toLowerCase();const box=$('#searchResults');if(!q){box.innerHTML=works.map(w=>`<a class="search-item" href="#/work/${w.id}" onclick="closeSearch()"><strong>${w.title}</strong><small>${w.genre.join(' · ')} · ${money(w.price)}</small></a>`).join('');return}let hits=[];for(const w of works){const wm=[w.title,w.subtitle,w.description,...w.characters,...w.genre].join(' ').toLowerCase();if(wm.includes(q))hits.push({href:`#/work/${w.id}`,title:w.title,sub:w.genre.join(' · ')});w.chapters.forEach((c,i)=>{if((c.title+' '+c.paragraphs.slice(0,8).join(' ')).toLowerCase().includes(q))hits.push({href:`#/read/${w.id}/${i}`,title:c.title,sub:w.title})})}box.innerHTML=hits.slice(0,30).map(h=>`<a class="search-item" href="${h.href}" onclick="closeSearch()"><strong>${h.title}</strong><small>${h.sub}</small></a>`).join('')||'<div class="empty">검색 결과가 없습니다.</div>'}
function closeSearch(){$('#searchLayer').hidden=true}window.closeSearch=closeSearch;
let signup=false;function openAuth(){signup=false;syncAuthModal();$('#authLayer').hidden=false}window.openAuth=openAuth;
function syncAuthModal(){$('#authTitle').textContent=signup?'회원가입':'로그인';$('#authSubmit').textContent=signup?'회원가입':'로그인';$('#authToggle').textContent=signup?'이미 계정이 있나요? 로그인':'처음이신가요? 회원가입';$('#authSetupNote').hidden=Auth.configured}
$('#authToggle').onclick=()=>{signup=!signup;syncAuthModal()};$('#authClose').onclick=()=>$('#authLayer').hidden=true;$('#authLayer').onclick=e=>{if(e.target===$('#authLayer'))$('#authLayer').hidden=true};
$('#authForm').onsubmit=async e=>{e.preventDefault();try{if(!Auth.configured)throw new Error('AUTH_NOT_CONFIGURED');const email=$('#authEmail').value.trim(),pw=$('#authPassword').value;const data=signup?await Auth.signUp(email,pw):await Auth.signIn(email,pw);if(signup&&!data.session)toast('확인 메일을 보냈습니다. 이메일 인증 후 로그인해주세요.');else toast(signup?'회원가입 완료!':'로그인 완료!');$('#authLayer').hidden=true}catch(err){toast(err.message==='AUTH_NOT_CONFIGURED'?'Supabase 설정을 먼저 연결해야 합니다.':(err.message||'인증 중 오류가 발생했습니다.'))}};
$('#accountBtn').onclick=()=>authState.user?location.hash='#/profile':openAuth();$('#searchBtn').onclick=()=>openSearch();$('#mobileSearch').onclick=()=>openSearch();$('#searchClose').onclick=closeSearch;$('#searchInput').oninput=e=>renderSearch(e.target.value);$('#themeBtn').onclick=()=>{prefs.theme=prefs.theme==='dark'?'light':'dark';savePrefs()};$('#panelClose').onclick=()=>$('#readerPanel').hidden=true;$('#fontSize').oninput=e=>{prefs.fontSize=+e.target.value;savePrefs()};$('#lineHeight').oninput=e=>{prefs.lineHeight=+e.target.value;savePrefs()};$('#readerWidth').oninput=e=>{prefs.width=+e.target.value;savePrefs()};$$('#fontMode button').forEach(b=>b.onclick=()=>{prefs.font=b.dataset.font;savePrefs()});
window.addEventListener('scroll',()=>{const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);$('#scrollProgress').style.width=(scrollY/max*100)+'%';$('#siteHeader').classList.toggle('scrolled',scrollY>10);clearTimeout(window.__st);window.__st=setTimeout(trackReader,120)},{passive:true});window.addEventListener('hashchange',route);window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSearch();$('#authLayer').hidden=true;$('#readerPanel').hidden=true}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}});
Auth.onChange(s=>{authState=s;$('#accountBtn').textContent=s.user?'MY':'로그인';route()});route();