
const works = window.HOPPANG_WORKS || [];
const $ = (s, el=document) => el.querySelector(s);
const $$ = (s, el=document) => [...el.querySelectorAll(s)];
const store = {
  get(k,d=null){try{return JSON.parse(localStorage.getItem(k)) ?? d}catch{return d}},
  set(k,v){localStorage.setItem(k,JSON.stringify(v))}
};
const prefs = Object.assign({theme:'dark',fontSize:19,lineHeight:1.9,width:760,font:'serif'},store.get('hoppang:prefs',{}));
const root=document.documentElement;
function applyPrefs(){
  root.classList.toggle('light',prefs.theme==='light');
  root.style.setProperty('--reader-size',prefs.fontSize+'px');
  root.style.setProperty('--reader-lh',prefs.lineHeight);
  root.style.setProperty('--reader-width',prefs.width+'px');
  const a=$('.reader-article'); if(a) a.classList.toggle('sans',prefs.font==='sans');
  const fs=$('#fontSize'), lh=$('#lineHeight'), rw=$('#readerWidth');
  if(fs){fs.value=prefs.fontSize;$('#fontSizeOut').textContent=prefs.fontSize+'px'}
  if(lh){lh.value=prefs.lineHeight;$('#lineHeightOut').textContent=Number(prefs.lineHeight).toFixed(2)}
  if(rw){rw.value=prefs.width;$('#widthOut').textContent=prefs.width+'px'}
  $$('#fontMode button').forEach(b=>b.classList.toggle('active',b.dataset.font===prefs.font));
}
applyPrefs();
function savePrefs(){store.set('hoppang:prefs',prefs);applyPrefs()}
function coverHTML(w,small=false){return `<div class="cover ${w.cover} ${small?'continue-thumb':''}"><div class="cover-copy"><span class="cover-kicker">${w.badge}</span><div class="cover-title">${w.title}</div><div class="cover-sub">${w.subtitle}</div></div></div>`}
function footer(){return `<footer class="footer"><span>© 2026 호빵문고 · 이 사이트의 작품은 이 대화에서 함께 만든 창작물입니다.</span><span>광고 없음 · 결제 없음 · 로그인 없음</span></footer>`}
function chapterLabel(i,w){const c=w.chapters[i]; return c ? c.title : ''}
function lastRead(){return store.get('hoppang:lastRead',null)}
function home(){
  const featured=works[0], lr=lastRead();
  let cont='';
  if(lr){const w=works.find(x=>x.id===lr.workId); if(w){const c=w.chapters[lr.chapter]||w.chapters[0];cont=`<section class="section"><div class="section-head"><div><h2>계속 읽기</h2><p>마지막으로 읽던 곳에서 바로 이어집니다.</p></div></div><div class="continue-card"><a href="#/work/${w.id}">${coverHTML(w,true)}</a><div class="continue-meta"><small>${w.title}</small><h3>${c.title}</h3><p>${Math.round((lr.progress||0)*100)}% 읽음</p><div class="mini-progress"><span style="width:${Math.round((lr.progress||0)*100)}%"></span></div></div><a class="primary-btn" href="#/read/${w.id}/${lr.chapter}">이어 읽기 →</a></div></section>`}}
  return `<section class="hero"><div class="hero-copy"><span class="eyebrow">HOPPANG ORIGINAL · 전편 무료</span><h1>김치는 맵고,<br><em>사랑은 더 뜨겁다.</em></h1><p>${featured.description}</p><div class="actions"><a class="primary-btn" href="#/read/${featured.id}/0">▶ 지금 읽기</a><a class="secondary-btn" href="#/work/${featured.id}">작품 정보</a></div></div><div class="hero-art">${coverHTML(featured)}</div></section>
  ${cont}
  <section class="section"><div class="section-head"><div><h2>호빵문고 오리지널</h2><p>우리가 만든 이야기를 한곳에서 무료로.</p></div><a class="text-link" href="#/library">전체 보기 →</a></div><div class="works-grid">${works.map(workCard).join('')}</div></section>
  <section class="about-strip"><div><h3>읽는 데 필요한 건 아무것도 없습니다.</h3><p>회원가입도, 결제도, 광고도 없습니다. 읽은 위치와 화면 설정은 이 기기에만 저장됩니다.</p></div><div class="stats"><div class="stat"><b>${works.length}</b><span>공개 작품</span></div><div class="stat"><b>${works.reduce((a,w)=>a+w.chapters.length,0)}</b><span>전체 챕터</span></div><div class="stat"><b>₩0</b><span>영원히 무료</span></div></div></section>${footer()}`;
}
function workCard(w){return `<a class="work-card" href="#/work/${w.id}">${coverHTML(w)}<div class="work-info"><h3>${w.title}</h3><p>${w.subtitle}</p><div class="chips">${w.genre.slice(0,3).map(g=>`<span class="chip">${g}</span>`).join('')}</div></div></a>`}
function library(){return `<div class="page-wrap"><span class="eyebrow">LIBRARY</span><h1 class="page-title">모든 작품</h1><p class="page-desc">호빵시티의 막장 멜로드라마부터 김우콩의 사회성 붕괴 기록까지. 전 작품 무료 공개.</p><div class="works-grid library-grid">${works.map(workCard).join('')}</div></div>${footer()}`}
function workDetail(id){const w=works.find(x=>x.id===id);if(!w)return notFound();const lr=lastRead();const start=lr&&lr.workId===w.id?lr.chapter:0;return `<section class="detail-hero"><div class="detail-cover">${coverHTML(w)}</div><div class="detail-copy"><span class="eyebrow">${w.badge} · ${w.status}</span><h1>${w.title}</h1><p class="subtitle">${w.subtitle}</p><div class="meta-row"><span class="meta-pill">${w.genre.join(' · ')}</span><span class="meta-pill">${w.rating}</span><span class="meta-pill">${w.chapters.length}개 챕터</span></div><p class="desc">${w.description}</p><div class="quote">“${w.quote}”</div><div class="characters">${w.characters.map(c=>`<span class="character">${c}</span>`).join('')}</div><div class="actions" style="margin-top:24px"><a class="primary-btn" href="#/read/${w.id}/${start}">${start>0?'▶ 이어 읽기':'▶ 처음부터 읽기'}</a><button class="secondary-btn" onclick="openSearch('${w.title.replace(/'/g,"\\'")}')">⌕ 작품 내 검색</button></div></div></section><section class="chapter-section"><div class="section-head"><div><h2>목차</h2><p>${w.chapters.length}개의 이야기</p></div></div><div class="chapter-list">${w.chapters.map((c,i)=>`<a class="chapter-row" href="#/read/${w.id}/${i}"><span class="chapter-num">${String(i+1).padStart(2,'0')}</span><strong>${c.title}</strong><span>${c.paragraphs.length}문단</span></a>`).join('')}</div></section>${footer()}`}
function reader(id,idx){const w=works.find(x=>x.id===id);idx=Number(idx)||0;if(!w||!w.chapters[idx])return notFound();const c=w.chapters[idx];setTimeout(()=>{applyPrefs();restoreScroll(w.id,idx)},0);return `<section class="reader-shell"><div class="reader-top"><div class="book-name"><a href="#/work/${w.id}">← ${w.title}</a></div><div class="chapter-name">${c.title}</div><div class="reader-actions"><button class="icon-btn" id="bookmarkBtn" title="북마크">☆</button><button class="icon-btn" id="settingsBtn" title="읽기 설정">Aa</button></div></div><article class="reader-article"><header class="reader-title"><small>${w.title}</small><h1>${c.title}</h1><p>${idx+1} / ${w.chapters.length}</p></header>${c.paragraphs.map(p=>`<p class="${p.includes('\n')?'poem':''}">${escapeHTML(p).replace(/\n/g,'<br>')}</p>`).join('')}<div class="reader-footer">${idx>0?`<a class="nav-chapter" href="#/read/${w.id}/${idx-1}"><small>← 이전</small>${w.chapters[idx-1].title}</a>`:'<span></span>'}${idx<w.chapters.length-1?`<a class="nav-chapter next" href="#/read/${w.id}/${idx+1}"><small>다음 →</small>${w.chapters[idx+1].title}</a>`:'<a class="nav-chapter next" href="#/work/'+w.id+'"><small>완독</small>작품 정보로 돌아가기</a>'}</div></article></section>`}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function notFound(){return `<div class="page-wrap"><span class="eyebrow">404</span><h1 class="page-title">페이지를 찾지 못했어요.</h1><p class="page-desc">호빵이 식기 전에 홈으로 돌아가세요.</p><a class="primary-btn" href="#/">홈으로</a></div>`}
function route(){window.scrollTo(0,0);const parts=(location.hash||'#/').slice(2).split('/');let view;if(parts[0]==='work')view=workDetail(parts[1]);else if(parts[0]==='read')view=reader(parts[1],parts[2]);else if(parts[0]==='library')view=library();else view=home();$('#app').innerHTML=view;bindDynamic();updateNav(parts[0]||'home')}
function bindDynamic(){const s=$('#settingsBtn');if(s)s.onclick=()=>{$('#readerPanel').hidden=false;applyPrefs()};const b=$('#bookmarkBtn');if(b){const [,,wid,ci]=(location.hash||'').split('/');const key=`${wid}:${ci}`;const marks=store.get('hoppang:bookmarks',[]);b.textContent=marks.includes(key)?'★':'☆';b.onclick=()=>{let m=store.get('hoppang:bookmarks',[]);if(m.includes(key))m=m.filter(x=>x!==key);else m.push(key);store.set('hoppang:bookmarks',m);b.textContent=m.includes(key)?'★':'☆'}}}
function updateNav(p){$$('[data-nav]').forEach(a=>a.classList.remove('active'));const key=p==='library'?'library':'home';$(`[data-nav="${key}"]`)?.classList.add('active')}
function restoreScroll(workId,chapter){const lr=lastRead();if(lr&&lr.workId===workId&&Number(lr.chapter)===Number(chapter)&&lr.scrollY){setTimeout(()=>window.scrollTo(0,Math.min(lr.scrollY,document.body.scrollHeight-window.innerHeight)),60)}}
function trackReader(){const hash=(location.hash||'').split('/');if(hash[1]!=='read')return;const workId=hash[2], chapter=Number(hash[3])||0;const max=Math.max(1,document.documentElement.scrollHeight-window.innerHeight);const progress=Math.min(1,window.scrollY/max);store.set('hoppang:lastRead',{workId,chapter,progress,scrollY:window.scrollY,at:Date.now()})}
let scrollTimer;window.addEventListener('scroll',()=>{$('#siteHeader').classList.toggle('scrolled',window.scrollY>12);const max=Math.max(1,document.documentElement.scrollHeight-window.innerHeight);$('#scrollProgress').style.width=(window.scrollY/max*100)+'%';clearTimeout(scrollTimer);scrollTimer=setTimeout(trackReader,120)},{passive:true});
function openSearch(seed=''){const layer=$('#searchLayer');layer.hidden=false;const input=$('#searchInput');input.value=seed;renderSearch(seed);setTimeout(()=>input.focus(),30)}window.openSearch=openSearch;
function renderSearch(q){const box=$('#searchResults');q=q.trim().toLowerCase();if(!q){box.innerHTML='<div class="empty">작품명, 인물, 챕터 제목을 검색해보세요.<br><span class="kbd">ESC</span>로 닫을 수 있어요.</div>';return}let hits=[];for(const w of works){const wm=[w.title,w.subtitle,w.description,...w.characters,...w.genre].join(' ').toLowerCase();if(wm.includes(q))hits.push({href:`#/work/${w.id}`,title:w.title,sub:w.subtitle});w.chapters.forEach((c,i)=>{const hay=(c.title+' '+c.paragraphs.slice(0,10).join(' ')).toLowerCase();if(hay.includes(q))hits.push({href:`#/read/${w.id}/${i}`,title:c.title,sub:w.title})})}hits=hits.slice(0,30);box.innerHTML=hits.length?hits.map(h=>`<a class="search-item" href="${h.href}" onclick="closeSearch()"><strong>${h.title}</strong><small>${h.sub}</small></a>`).join(''):'<div class="empty">검색 결과가 없습니다.</div>'}
function closeSearch(){$('#searchLayer').hidden=true}window.closeSearch=closeSearch;
$('#searchBtn').onclick=()=>openSearch();$('#searchClose').onclick=closeSearch;$('#searchInput').addEventListener('input',e=>renderSearch(e.target.value));$('#searchLayer').addEventListener('click',e=>{if(e.target===$('#searchLayer'))closeSearch()});
$('#themeBtn').onclick=()=>{prefs.theme=prefs.theme==='dark'?'light':'dark';savePrefs()};$('#panelClose').onclick=()=>$('#readerPanel').hidden=true;$('#fontSize').oninput=e=>{prefs.fontSize=Number(e.target.value);savePrefs()};$('#lineHeight').oninput=e=>{prefs.lineHeight=Number(e.target.value);savePrefs()};$('#readerWidth').oninput=e=>{prefs.width=Number(e.target.value);savePrefs()};$$('#fontMode button').forEach(b=>b.onclick=()=>{prefs.font=b.dataset.font;savePrefs()});$('#resetPrefs').onclick=()=>{Object.assign(prefs,{fontSize:19,lineHeight:1.9,width:760,font:'serif'});savePrefs()};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSearch();$('#readerPanel').hidden=true}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}});window.addEventListener('hashchange',route);route();
